### PR TITLE
Created Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by f0rb1d**
I just created Simplified Chinese translation file for Androoster.
It's a awesome software on Android platform, containing plenty useful tweaks and beautiful Material Design UI. But it only has 3 sections for free users, which makes it a little bit harder to compete with other popular tweakers. I think you can open up more sections so that you will get more users to use this app, it's like a gold hidden in dust. Anyways, if you cannot maintain the app on your own, you can always call someone assist you to do the work.
Thanks for such brilliant software :D

### CODE REVIEW

**Comment by AndreaCioccarelli** [comment]
Going to update this in a few days.. Thanks! 😉

**Comment by f0rb1d** [comment]
@AndreaCioccarelli You're welcome. Such awesome software deserves to be translated in every language and distributed to everyone.
Also pls consider my suggestions :D

**Comment by f0rb1d** [comment]
By the way the translation string is wrong image

**Comment by AndreaCioccarelli** [comment]
Let me update the app with the new strings, I'll also change the strings over there

**Pull request merged**
